version: '3.8'

services:
  ava-monitor:
    build: .
    image: ava-monitor:latest
    container_name: ava-monitor
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
      - PYTHONUNBUFFERED=1
    networks:
      - infrastructure_default
    volumes:
      - ./AVAOperationLog.py:/app/AVAOperationLog.py
      # Pro zachování přihlašovacích údajů po restartu kontejneru (soubor na hostiteli musí před spuštěním existovat, např. přes touch avaplace_credentials.json)
      # - ./avaplace_credentials.json:/app/avaplace_credentials.json
    ports:
      - "8501:8501"

networks:
  infrastructure_default:
    external: true
