version: '3.8'

services:
  ava-monitor:
    build: .
    image: ava-monitor:latest
    container_name: ava-monitor
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
      - PYTHONUNBUFFERED=1
    networks:
      - infrastructure_default
    volumes:
      - .:/app
    ports:
      - "8501:8501"

networks:
  infrastructure_default:
    external: true
